spring.application.name=chat-web
#spring.config.import=env.properties

socket-server.port=8085
socket-server.host=127.0.0.1

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto= none
spring.datasource.url= jdbc:postgresql://localhost:5432/chating
spring.datasource.username= postgres
spring.datasource.password= 123456
spring.datasource.driver-class-name= org.postgresql.Driver